#!/bin/sh

# Destroy any previous container.
docker stop CT-NG >&- 2>&-
docker rm CT-NG >&- 2>&-

#docker run -it --name=CT-NG ct-ng "$@"
docker run --name=CT-NG --network=host -v /home/amauri/git/projects/carsystem/RadioHead:/root/project -it ct-ng bash
